[package]
name = "rustperft"
version = "0.1.0"
authors = ["Peter Ellis Jones <pete@peterellisjones.com>"]

[dependencies]
chess-move-gen = "^0.3.9"
prettytable-rs = "*"
clap = "*"
threadpool = "*"
num_cpus = "*"
unindent = "*"